defmodule Nietflix.Repo.Migrations.CreateIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:post, [:author_id])

    create index(:comment, [:post_id])
  end

  def down do
    drop_if_exists(index(:comment, [:post_id]))

    drop_if_exists(index(:post, [:author_id]))
  end
end
